- name: Generate ignition configs
  import_role:
    name: openshift_common
    tasks_from: generate_ignition.yml

- name: Compute virtual machine names
  import_role:
    name: openshift_common
    tasks_from: compute_vm_names.yml

- name: Ensure prerequisites
  import_tasks: ensure_prereqs.yml

- name: Deploy hosts
  import_tasks: deploy_hosts.yml

- name: Wait for ssh on OpenShift hosts
  import_role:
    name: openshift_common
    tasks_from: wait_for_ssh.yml
  vars:
    wait_for_ssh_existing_vms: '{{ libvirt_existing_vms }}'

- name: Wait for the bootstrap to complete
  import_role:
    name: openshift_common
    tasks_from: wait_for_bootstrap.yml
