# OpenShift Installer configuration
openshift_install_config:
  # Version of OpenShift to be installed.
  version: 4.3.8
  # Version of the CoreOS image.
  coreos_version: 4.3.8
  # Unique name of the OpenShift cluster which also becomes a part of cluster's FQDN.
  name: mycluster
  # Base domain which is appended to the cluster's name to form a cluster FQDN.
  base_domain: example.com
  # FQDN of the OpenShift cluster. It must be in the format <name>.<base_domain>
  cluster_domain: hubcls.example.com
  # Number of master nodes. Set this to 3 to achieve a highly-available control plane.
  master_replicas: 3
  # Number of worker nodes equals to the number of infra nodes + the number of app nodes.
  # Typical production installation will have 3 infra nodes. Regardless of how many
  # worker nodes you will deploy, you must set the value of the replicas parameter to 0.
  # This parameter controls the number of workers that the cluster creates and manages
  # for you, which are functions that the cluster does not perform when you use
  # user-provisioned infrastructure.
  worker_replicas: 2
  # This URL will be accessed by the OpenShift nodes during the bootstrap in order
  # for them to download their ignition files. Make sure that this URL is reachable
  # from the OpenShift nodes.
  ignition_url_prefix: 'http://192.168.150.2:81/openshift-auto-upi/mycluster'
  # Configure OpenShift hosts using static IPs as opposed to using DHCP.
  # This feature is currently supported for bare metal, libvirt_pxe, oVirt, and vSphere.
  # It is not supported for libvirt_fwcfg.
  # For bare metal and libvirt_pxe, the PXE menu config is modified to include the
  # static IP configuration.
  # For oVirt and vSphere, a boot ISO is created that includes a custom GRUB boot loader
  # configuration that includes the static IP configuration. This custom GRUB confguration
  # is used only during the first boot of the OpenShift hosts. Following boots will go
  # back to using the factory GRUB configuration.
  static_ips:
    # Must enable in order to use the static IP provisioning.
    enabled: True
    parameters:
      gateway: 192.168.150.1
      netmask: 255.255.255.0
      # On oVirt and libvirt the interface name is most likely "ens3". On vSphere the
      # interface name is most likely "ens192".
      interface: ens192
      # List of DNS servers
      nameservers:
        - 192.168.150.1
  # When you deploy the cluster, this public SSH key is added to the core user’s
  # ~/.ssh/authorized_keys list. You can use this key to SSH into the OpenShift hosts
  # as the user core.
  ssh_key: ''
  # This is a JSON formatted pull secret that you can obtain at
  # https://cloud.redhat.com when installing a new OpenShift cluster. There is a
  # button "Download pull secret" that downloads this pull secret for you.
  # The secret contains keys for downloading container images from several Red Hat
  # repositories like quay.io, registry.connect.redhat.com, registry.redhat.io and
  # also keys for authenticating against the cloud.openshift.com itself.
  pull_secret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2xsaXhpbm4xYmFoeXkzYzlneGVjNHp2bHhvZG01OTVya286NkhNOEswR0oxTDdMNzhYTTBNOVUwU1NFTkxGSERZMjMzT0VUOVVEV1NQVjZPTkdYNE83QVI0Tzc4R1dYMjlBRw==","email":"llixinn@cn.ibm.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2xsaXhpbm4xYmFoeXkzYzlneGVjNHp2bHhvZG01OTVya286NkhNOEswR0oxTDdMNzhYTTBNOVUwU1NFTkxGSERZMjMzT0VUOVVEV1NQVjZPTkdYNE83QVI0Tzc4R1dYMjlBRw==","email":"llixinn@cn.ibm.com"},"registry.connect.redhat.com":{"auth":"NTMwNDkwMTF8dWhjLTFiQWh5eTNjOUdYRWM0WnZMeE9kTTU5NVJrbzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTJZVGcxTmpJM1kyRm1NV0kwTTJReFlUWm1OR0V4TkdOak5EUTVaRGszWXlKOS5zU0kzMncwS0xJYlh5akZNWW5DZjk4NVk2SU9hN0tDRmgtTENzcnVOemNIcGJGLTVYT2Ewem1NVDVxbW53RlNONC1DTFJPeC1Ba1BtM2JkZ2dBQWFoM3ZLQ0xGLVNMM1hESF94VGxxOXM0RUQwdnk4R3lMMWxRbElUOV8zMmtYUjIwVUg4djhDVWJXRXZteGVmUXFlaGcwVmp2TnhzeE8xdjJZVEpPcWo5ZmgwV1FuTTVmZjBwOW41Y0VTQVA5eFFCc25BSzRLUnU4RERJMU5kUHVJQVRNaGZsS3ItTkI2Q3VPSERPRUZCQzdXcjRoVmxFblBWZVVYS05rNVk1M09WMjhpdndFcmVseDd3ODBKMm1EaFduY3lMM2Fuc0pXRG9oUDlKV2NTcTZUNDdPbFk4M0pZazBYVTVLVXE3MDV2cmp5eXFHUE9veVJqU3VPQWw0ekpGUTNOdTQzdE8teU5YcS00aVZINXExQnp6akYwMzdfSkdyQ3VvT2g1NkY0ampSWDRLX1hYaGhnYk5na1ptR25SWXpyTW42b0lrRGFySncwQ2w1cjBlbXczSThrSmMxME5SNjktdnhWSlpsS25kMUE5UjBzN1dUblZQbEJQUnlSMUxkNkQtdW9IY2htRjRlV0d1RzNJYXBTMHE2TzRZTDJqMkFQY05Ndndlb1ZDU01YMWd6cGo4VXNvSmlHRkl6MHJUcW1pRC1mdG45aEY1Vi15Y1JwWk9xY0M3RmVkWW9ubGVvUnV4bUlUNGJuUkk0Y0VETGpiN1VNRHVTNHRSZDNqYkx0bU4wcnByY2xza3VnNjNuRF9FbDBuQ3k0aERVQkYzU0FwT2FaYXBmMmh1ZnFoNmp1dXEyX0Y0VHdJTmxsWWFFbVlaYTV2V1pMLUdMYmlHMF9IZjB6VQ==","email":"llixinn@cn.ibm.com"},"registry.redhat.io":{"auth":"NTMwNDkwMTF8dWhjLTFiQWh5eTNjOUdYRWM0WnZMeE9kTTU5NVJrbzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTJZVGcxTmpJM1kyRm1NV0kwTTJReFlUWm1OR0V4TkdOak5EUTVaRGszWXlKOS5zU0kzMncwS0xJYlh5akZNWW5DZjk4NVk2SU9hN0tDRmgtTENzcnVOemNIcGJGLTVYT2Ewem1NVDVxbW53RlNONC1DTFJPeC1Ba1BtM2JkZ2dBQWFoM3ZLQ0xGLVNMM1hESF94VGxxOXM0RUQwdnk4R3lMMWxRbElUOV8zMmtYUjIwVUg4djhDVWJXRXZteGVmUXFlaGcwVmp2TnhzeE8xdjJZVEpPcWo5ZmgwV1FuTTVmZjBwOW41Y0VTQVA5eFFCc25BSzRLUnU4RERJMU5kUHVJQVRNaGZsS3ItTkI2Q3VPSERPRUZCQzdXcjRoVmxFblBWZVVYS05rNVk1M09WMjhpdndFcmVseDd3ODBKMm1EaFduY3lMM2Fuc0pXRG9oUDlKV2NTcTZUNDdPbFk4M0pZazBYVTVLVXE3MDV2cmp5eXFHUE9veVJqU3VPQWw0ekpGUTNOdTQzdE8teU5YcS00aVZINXExQnp6akYwMzdfSkdyQ3VvT2g1NkY0ampSWDRLX1hYaGhnYk5na1ptR25SWXpyTW42b0lrRGFySncwQ2w1cjBlbXczSThrSmMxME5SNjktdnhWSlpsS25kMUE5UjBzN1dUblZQbEJQUnlSMUxkNkQtdW9IY2htRjRlV0d1RzNJYXBTMHE2TzRZTDJqMkFQY05Ndndlb1ZDU01YMWd6cGo4VXNvSmlHRkl6MHJUcW1pRC1mdG45aEY1Vi15Y1JwWk9xY0M3RmVkWW9ubGVvUnV4bUlUNGJuUkk0Y0VETGpiN1VNRHVTNHRSZDNqYkx0bU4wcnByY2xza3VnNjNuRF9FbDBuQ3k0aERVQkYzU0FwT2FaYXBmMmh1ZnFoNmp1dXEyX0Y0VHdJTmxsWWFFbVlaYTV2V1pMLUdMYmlHMF9IZjB6VQ==","email":"llixinn@cn.ibm.com"}}}'
