- name: Is firewalld running?
  command: firewall-cmd --state
  changed_when: False
  failed_when: False
  register: firewalld
  become: True

- name: Enable dns service on firewall
  firewalld:
    service: dns
    permanent: True
    immediate: True
    state: enabled
  when: firewalld.rc == 0
  become: True

- name: Add OpenShift DNS records
  template:
    src: '{{ item.src }}'
    dest:  '{{ item.dest }}'
  with_items:
    - { src: dnsmasq.openshift-auto-upi.dns.conf, dest: /etc/dnsmasq.d }
    - { src: dnsmasq.openshift-auto-upi.addnhosts, dest: /etc }
  notify: Restart dnsmasq
  become: True
