- name: Install pyghmi required by Ansible
  yum:
    name: '{{ rpm_name["python-pyghmi"] }}'
    state: present
  become: True

- name: Ensure PXE prerequisites
  import_role:
    name: openshift_common
    tasks_from: ensure_pxe_prereqs.yml
